# Generated by Django 5.2.3 on 2025-06-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
