# Generated by Django 5.2.3 on 2025-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='year',
        ),
        migrations.AddField(
            model_name='year',
            name='name',
            field=models.CharField(default=2025, max_length=10),
            preserve_default=False,
        ),
    ]
